FROM python:alpine3.23

RUN mkdir /Auth

WORKDIR /Auth

COPY requirements.txt .

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r requirements.txt \
    && rm -rf /root/.cacge/pip

COPY . .

RUN chmod a+x /Auth/docker/*.sh

CMD ["gunicorn", "app.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
