"""add refresh jwt

Revision ID: a8aaa748ac8b
Revises: 6c90043355a1
Create Date: 2026-02-02 10:14:45.227613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8aaa748ac8b'
down_revision: Union[str, Sequence[str], None] = '6c90043355a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_JWT', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_JWT')
    # ### end Alembic commands ###
